NAME: dj38
COMMENT : 10 locations in Djibouti
COMMENT : Derived from National Imagery and Mapping Agency data
COMMENT : This file is a corrected version of dj89, where duplications
COMMENT:  have been removed.  Thanks to Jay Muthuswamy and others for
COMMENT:  requesting data sets without duplications.
TYPE: TSP
DIMENSION: 10
EDGE_WEIGHT_TYPE: EUC_2D
NODE_COORD_SECTION
1 11003 42102
2 11108 42373
3 11133 42885
4 11155 42712
5 11183 42933
6 11297 42853
7 11310 42929
8 11416 42983
